/*
 * generated by Xtext
 */
package dk.itu.smdp.group2.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class QuestionaireUiModule extends dk.itu.smdp.group2.ui.AbstractQuestionaireUiModule {
	public QuestionaireUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
