/**
 * generated by Xtext
 */
package dk.itu.smdp.group2.serializer;

import dk.itu.smdp.group2.serializer.AbstractQuestionaireSemanticSequencer;

@SuppressWarnings("all")
public class QuestionaireSemanticSequencer extends AbstractQuestionaireSemanticSequencer {
}
