/**
 * generated by Xtext
 */
package dk.itu.smdp.group2.serializer;

import dk.itu.smdp.group2.serializer.AbstractQuestionaireSyntacticSequencer;

@SuppressWarnings("all")
public class QuestionaireSyntacticSequencer extends AbstractQuestionaireSyntacticSequencer {
}
