/*
* generated by Xtext
*/
package dk.itu.smdp.group2.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class QuestionaireAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("dk/itu/smdp/group2/parser/antlr/internal/InternalQuestionaire.tokens");
	}
}
