/*
* generated by Xtext
*/
package dk.itu.smdp.group2.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import dk.itu.smdp.group2.services.QuestionaireGrammarAccess;

public class QuestionaireParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private QuestionaireGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected dk.itu.smdp.group2.parser.antlr.internal.InternalQuestionaireParser createParser(XtextTokenStream stream) {
		return new dk.itu.smdp.group2.parser.antlr.internal.InternalQuestionaireParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Questionaire";
	}
	
	public QuestionaireGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(QuestionaireGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
