/*
 * generated by Xtext
 */
package dk.itu.smdp.group2;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QuestionaireRuntimeModule extends dk.itu.smdp.group2.AbstractQuestionaireRuntimeModule {

}
