/*
 * generated by Xtext
 */
package dk.itu.smdp.group2;

import org.eclipse.xtext.conversion.IValueConverterService;

import dk.itu.smdp.group2.converter.TextQuestionLengthConverter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QuestionaireRuntimeModule extends dk.itu.smdp.group2.AbstractQuestionaireRuntimeModule {

	@Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return TextQuestionLengthConverter.class;
    }
}
