/**
 * generated by Xtext
 */
package dk.itu.smdp.group2.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class QuestionaireProposalProvider /* implements AbstractQuestionaireProposalProvider  */{
}
