/**
 * generated by Xtext
 */
package dk.itu.smdp.group2.validation;

import dk.itu.smdp.group2.validation.AbstractQuestionaireValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class QuestionaireValidator extends AbstractQuestionaireValidator {
}
