/*
 * generated by Xtext
 */
package dk.itu.smdp.group2.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import dk.itu.smdp.group2.ui.internal.QuestionaireActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class QuestionaireExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return QuestionaireActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return QuestionaireActivator.getInstance().getInjector(QuestionaireActivator.DK_ITU_SMDP_GROUP2_QUESTIONAIRE);
	}
	
}
